name: Test Coverage Report
on: [ pull_request ]

jobs:
  test_coverage:
    runs-on: ubuntu-latest
    #    runs-on: self-hosted

    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Setup LCOV
        uses: hrishikesh-kadam/setup-lcov@v1

      - name: Get Flutter dependencies
        run: |
          flutter pub get
          flutter pub add --dev test_cov_console

      - name: Run build_runner
        run: dart run build_runner build --delete-conflicting-outputs --verbose

      - name: Run tests with coverage
        run: flutter test --coverage

      - name: Filter ViewModel files
        run: |
          lcov --extract coverage/lcov.info "lib/**/*_viewmodel.dart" -o coverage/filtered_lcov.info

      - name: Report code coverage
        uses: zgosalvez/github-actions-report-lcov@v4
        with:
          coverage-files: coverage/filtered_lcov.info
          #          minimum-coverage: 90
          artifact-name: code-coverage-report
          github-token: ${{ secrets.GITHUB_TOKEN }}
          update-comment: true
